name: Get Data and Deploy

on:
  #push:
  #branches: [ main ]
  schedule:
    - cron: "0 23 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-data:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.0.1" "requests==2.29.0" "numpy==1.24.3"
      - run: python get_extraData.py
      - name: Update master
        run: |
          git config --global user.name 'z-Wind'
          git config --global user.email 'zpsyhapcst@gmail.com'
          git add .
          git diff --cached --exit-code || git commit -m "Regularly update extra Data"
          git push

  deploy:
    needs: get-data
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "yfinance==0.2.40" "pandas==2.0.3" "pyquery==2.0.0" "flask==3.0.3" "plotly==5.22.0" "requests==2.32.3" "numpy==1.24.4"

      - working-directory: ./FFI/rust_lib
        run: cargo build --release
      - run: python stock.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: report # The folder the action should deploy.
