name: Get Data and Deploy

on:
  #push:
  #branches: [ main ]
  schedule:
    - cron: "0 23 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-data:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.2.2" "requests==2.32.3" "numpy==2.1.0"
      - run: python get_extraData.py
      - name: Update master
        run: |
          git config --global user.name 'z-Wind'
          git config --global user.email 'zpsyhapcst@gmail.com'
          git add .
          git diff --cached --exit-code || git commit -m "Regularly update extra Data"
          git push

  deploy:
    needs: get-data
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "yfinance>=0.2,<0.3" "pandas==2.2.2" "pyquery==2.0.0" "flask==3.0.3" "plotly==5.23.0" "requests==2.32.3" "numpy==2.1.0" "maturin==1.7.0" "pyxirr==0.10.5"

      - working-directory: ./FFI/rust_pyo3
        run: |
          maturin build --release
          python -m pip install ./target/wheels/rust_pyo3-*.whl
      - run: |
          python stock.py
          python tw_analysis.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report    # The folder the action should deploy.
          publish_branch: gh-pages # The branch the action should deploy to.
